### ISSUE TITLE
Method to disconnect blocknative or emitter

### ISSUE THREAD

**Issue by pguardiario** [blocknative/sdk#187]
Is there one? This would be helpful to put in the README

**Comment by aaronbarnardsound** [comment]
If you would like to disconnect the WebSocket connection, you can call `blocknative.destroy()`. If you would like to unsubscribe to events for an address or transaction hash, you can call `blocknative.unsubscribe(addressOrHash)`.
If you would like to remove a listener from the emitter, then you can call the `emitter.off` method.

**Comment by pguardiario** [comment]
Thanks Aaron,
Can you confirm that websocket errors will try to reconnect and that the
emitters will keep working when that happens?

**Comment by aaronbarnardsound** [comment]
@pguardiario Sorry for the late response here. Yes if the socket connection drops it will automatically try to reconnect and you can log when these events happen by passing in an `onreopen` handler. Once it reconnects, the sdk will automatically re-watch all subscription items (since that state on the server is lost when the connection drops) and all emitters should work as normal (since they are kept in memory).

**Comment by aaronbarnardsound** [comment]
Closing this issue for now, but feel free to reopen if there is action required.
